name: Hoplite deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Create a commit SHA-based tag for DockerHub
      - name: Create SHA Container Tag
        id: sha_tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "tag=$tag" >> $GITHUB_OUTPUT

      # Check out master branch
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}
      
      # Build and push the container to DockerHub
      # The container will be tagged as "latest" and with the short SHA of the commit.
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: docker/tyrant.Dockerfile
          push: true
          cache-from: type=registry,ref=lemonsaurus/tyrant:latest
          cache-to: type=inline
          tags: |
            lemonsaurus/tyrant:latest
            lemonsaurus/tyrant:${{ steps.sha_tag.outputs.tag }}
          build-args: |
            git_sha=${{ steps.sha_tag.outputs.tag }}

      # Deploy via Hoplite
      - name: Send a webhook to Hoplite
        uses: distributhor/workflow-webhook@v2.0.2
        env:
          webhook_auth: ${{ secrets.webhook_auth }}
          webhook_secret: ${{ secrets.webhook_secret }}
          webhook_url: ${{ secrets.webhook_url }}
          data: '{"service": "tyrant"}'
